module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
  ],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@aiken/collection$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/collection/index.ts',
    '^@aiken/crypto$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/crypto.ts',
    '^@aiken/math$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/math/index.ts',
    '^@aiken/cbor$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/cbor.ts',
    '^@aiken/primitive$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/primitive/index.ts',
    '^@aiken/interval$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/interval.ts',
    '^@aiken/option$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/option.ts',
    '^@aiken/rational$': '<rootDir>/src/core/packages/aiken-lang/stdlib/v2.2.0/lib/aiken/math/rational.ts',
    '^@aiken/fuzz$': '<rootDir>/src/core/packages/aiken-lang/fuzz/v2.2.0/lib/aiken/fuzz/index.ts',
    '^@aiken/prelude$': '<rootDir>/src/core/packages/aiken-lang/prelude/v1.0.0/lib/aiken/index.ts',
    '^@aiken/merkle-patricia-forestry$': '<rootDir>/src/core/packages/aiken-lang/merkle-patricia-forestry/v2.1.0/lib/aiken/merkle-patricia-forestry/index.ts',
    '^@aiken/helpers$': '<rootDir>/src/core/packages/aiken-lang/merkle-patricia-forestry/v2.1.0/lib/aiken/merkle-patricia-forestry/helpers.ts',
    '^@aiken/merkling$': '<rootDir>/src/core/packages/aiken-lang/merkle-patricia-forestry/v2.1.0/lib/aiken/merkle-patricia-forestry/merkling.ts',
    '^@cardano/(.*)$': '<rootDir>/src/core/packages/aiken-lang/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
  },
};
